public-key: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAKC3RBPoDeV0BERl7NqNAOombVmp+vxNeO0Y2PVagIeE80sPxNyTBQMz1WPPMaSd3iEcdBUpavtLR3uyC2vfe3UCAwEAAQ==
  #datasource
spring:
  #datasource
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://39.96.181.151:3306/blog?characterEncoding=utf8&useSSL=true
    username: root
    password: mVf7NMRzEmPVYAM9LXMKee7VxNXtSY5NNmXfLQQikQPum9bJ3dd+C1BfuH48XY/MasZyyDPBccb3LTQJrkd1yA==
    druid:
      initial-size: 5
      max-active: 20
      min-idle: 5
      filters: config,stat,slf4j
      filter:
        config:
          enabled: true
      connection-properties: config.decrypt=true;config.decrypt.key=${public-key}
      test-on-borrow: true
      test-on-return: true
      test-while-idle: true
  redis:
    host: 192.168.50.186
    port: 6379
    password: wonyen@1602
    timeout: 5000
    jedis:
      pool:
        max-idle: 500
        min-idle: 50
        max-active: 1000
        max-wait: 2s
xdx: xdxxdxxdx

