spring:
  output:
    ansi:
      enabled: always
  thymeleaf:
    cache: false
  profiles:
    active:
      - '@environment@'
#日志
logging:
  config: classpath:logback.xml
  level:
    com.xdx.dao: trace
mybatis:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.xdx.model
  type-handlers-package: com.xdx.handler
  configuration:
    map-underscore-to-camel-case: true
pagehelper:
  helperDialect: mysql
  supportMethodsArguments: true
  params: count=countSql
  reasonable: true
  page-size-zero: true